services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo
      POSTGRES_DB: echo
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U echo"]
      interval: 5s
      timeout: 5s
      retries: 20
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8080"]
