apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app: {{ include "web.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "web.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
