apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments.fullname" . }}
  labels:
    app: {{ include "payments.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "payments.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4300
      protocol: TCP
      name: http
