name: ci
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Show pnpm version
        run: pnpm --version

      - name: Install dependencies (no frozen lockfile)
        run: pnpm install --no-frozen-lockfile

      - name: Build (workspace with fallbacks)
        run: |
          pnpm -w build || pnpm -w -r build || pnpm --filter web build
