name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Go Test
        run: |
          go test ./apps/services/orders/...
          go test ./apps/services/payments/...
          go test ./apps/services/logistics/...
      - name: Python Tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r apps/agents/requirements-dev.txt
          pytest apps/agents/tests
