apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    app: {{ include "catalog.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "catalog.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4100
      protocol: TCP
      name: http
